main: owenxr.main.Main
version: 0.5.1
name: MazeMinigame
api-version: 1.17

commands:
  create:
    description: Creates maze
  wand:
    description: Gives wand
  start:
    description: Starts Game
